### ISSUE TITLE
Issue creating worlds.

### ISSUE THREAD

**Issue by Anidioto** [Ladysnake/Astronomical#1]
When ever I go to create a creative world, the game either freezes the loading process, or B: tries to send me into a multiplayer world. I don't know I'm doing wrong and I'm using only Astronomical in my mod setup.

**Comment by ComputerFrog** [comment]
Same happening here

**Comment by Anidioto** [comment]
![image_2024-01-15_154703054](https://github.com/Ladysnake/Astronomical/assets/156714935/76ae71f5-80b9-443e-995c-148e9973f3d4)
heres a screen shot of it happening

**Comment by ComputerFrog** [comment]
Yeah that's what is happening to me too

**Comment by LafontaineBray** [comment]
Same here

**Comment by Pyrofab** [comment]
Seems like the fix is to install [Cardinal Components API](https://modrinth.com/mod/cardinal-components-api) separately

**Comment by ComputerFrog** [comment]
Yes, that works!

**Comment by SalTeyJek004** [comment]
the true issue is an unlabeled cardinal components dependecy then?

**Comment by Pyrofab** [comment]
Seems like the real issue is that Astronomical bundled a faulty version of CCA, but yes as a quickfix I added the required dependency on Modrinth

**Comment by Anidioto** [comment]
ah ok thanks!
