### ISSUE TITLE
Storm on the Eye of the universe fails to render.

### ISSUE THREAD

**Issue by TheFurru** [Ladysnake/Astronomical#12]
No clue why this is happening, but here's a screenshot.

![2024-01-17_18 09 57](https://github.com/Ladysnake/Astronomical/assets/84253895/a4d342ff-7880-4854-a9ee-cb8fbfb0dd94)

I can see the sphere just fine, but the storm refuses to appear.

**Comment by UpcraftLP** [comment]
Hey, does this happen with just Astronomical, or are there other mods present?

**Comment by TheFurru** [comment]
> Hey, does this happen with just Astronomical, or are there other mods present?

Just Astronomical, and the dependencies installed as separate mods. I really like the design of it as seen in the video, and was gonna use a stupidly upscaled version of it to cover the sky of my world, but that cant be done without the storm, and ive no clue why it isnt rendering properly.

**Comment by TheFurru** [comment]
This fixed itself after i re-installed quilt loader.
