### ISSUE TITLE
SUGGESTION : Allow lightning in the storm of the Eye of the universe to also appear on the bottomside.

### ISSUE THREAD

**Issue by TheFurru** [Ladysnake/Astronomical#14]
Just so i can have some fun with my friends with the eye of the universe in the sky making it a constant storm, you cannot see the lightning strikes from the bottom, though.

**Comment by doctor4t** [comment]
With transparency being very scuffed in Astronomical and Minecraft, as well as me wanting to optimize the eye as it's using a lot of element, this isn't really a good idea as it would reduce performance and possibly not work consistently.
