### ISSUE TITLE
marshmallow ui

### ISSUE THREAD

**Issue by JamesBond101** [Ladysnake/Astronomical#16]
https://github.com/Ladysnake/Astronomical/assets/157222876/db7fecaf-1f92-4cd4-89d6-b59f1f3f7236

the ui of the marshmallow is only showing up in creative

**Comment by att1cu3** [comment]
I think that's intentional

**Comment by JamesBond101** [comment]
I don't think that's intentional because you don't see the display in
survival mode where you should see it because that's where you need it.
However, in creative mode you don't really need them because you can simply
get the different types from your inventory.

att1cu3 ***@***.***> schrieb am Di., 23. Jan. 2024, 20:02:

**Comment by JustRed23** [comment]
![image](https://github.com/Ladysnake/Astronomical/assets/21986809/8b18b17f-8a92-4eae-9185-f6626f5807c5)
In the comments of the showcase vid

**Comment by JamesBond101** [comment]
Oh i didn't see that, thanks

JustRed23 ***@***.***> schrieb am Do., 25. Jan. 2024, 22:12:

**Comment by doctor4t** [comment]
Intentional. The GUI was originally added for debug reasons, but we kept it in creative mode so that people could train with the timing.
