### ISSUE TITLE
[Suggestion] Enable Marshmallow Cans to hold more than one stack

### ISSUE THREAD

**Issue by Gronglegrowth** [Ladysnake/Astronomical#17]
Currently the Marshmallow Can can hold up to one stack of Marshmallows. I had initially assumed they would be able to store more than this, and I would like this to be the case - maybe two or three stacks more?

**Comment by doctor4t** [comment]
Marshmallow cans are easily obtainable, and their value doesn't reside in their capacity. The only goal of cans is to place them down for roleplay reasons and for ease of putting marshmallows on sticks without using crafting, not as mashmallow shulker boxes.
