### ISSUE TITLE
[Bug Report] Game crashing when placing Create schematics and when the "ponder" screen is opened

### ISSUE THREAD

**Issue by MintySweeteaReal** [Ladysnake/Astronomical#19]
When trying to open the pondering screen or when placing a schematic with Astronomical and Create fabric installed the game will briefly freeze, then go to the "Saving World" screen for a few seconds after which the game crashes.

[create schematic crash report.txt](https://github.com/Ladysnake/Astronomical/files/14015449/create.schematic.crash.report.txt)

**Comment by Pyrofab** [comment]
Duplicate of #6
