### ISSUE TITLE
BUG REPORT: Game crashes on launch due to conflict with... the quilt modloader?

### ISSUE THREAD

**Issue by HexalTheDeltaDrake** [Ladysnake/Astronomical#21]
I'm not entirely sure how or why, but any time I attempt to run this mod, it causes a crash during launch. I've attempted to narrow it down to just Astronomical and the Quilt API, and Astronomical seems to cause "quilted_fabric_renderer_indigo" to completely fail.

Crash Report:
https://mclo.gs/oftToPc

Using Astronomical 1.0.1, Quilt Kotlin Libraries 1.0.2 and Quilted Fabric API 4.0.0

**Comment by doctor4t** [comment]
What's your quilt loader version?

**Comment by HexalTheDeltaDrake** [comment]
I'm not entirely sure, I'm using the modrinth app and it doesn't seem to show that anywhere. Its on 1.19.2 though, and its using the 4.0.0 beta version of the api

**Comment by HexalTheDeltaDrake** [comment]
Ok, I figured out where to find the modloader version on the Modrinth app, its 0.24.0-beta.8, the default "stable" version of quilt for the Modrinth app.

**Comment by Palmdemouse** [comment]
The new version of quilted fabric Api is causing the crashes. using an older version like the one from march fixes the crashes somehow.

**Comment by HexalTheDeltaDrake** [comment]
Ah, thank you! I'll be sure to downgrade the api when i try to play it next! Now... should I close this myself or should I let one of you do it?
