### ISSUE TITLE
Stops Minecraft from starting altogether no matter what I try

### ISSUE THREAD

**Issue by Inverse5040** [Ladysnake/Astronomical#25]
I have completely emptied my 1.19.2 installation of mods except for QFAPI + QSL, Cardinal Components API, and this mod. I've tried everything, from using either version of this mod, to rolling back the QFAPI version to several previous versions, to even rolling back the version of the quilt modloader to various previous versions, and multiple combinations of those attempted solutions.

**Comment by UpcraftLP** [comment]
Could you please provide a log?

**Comment by Xiribidus** [comment]
Considering no log as been provided I'll just close this
