### ISSUE TITLE
Illegal Acces Error ?

### ISSUE THREAD

**Issue by Lapis-Guy-Official** [Ladysnake/Astronomical#28]
Hi i got a issue with the mods it's say 
"java.lang.IllegalAccessError: class doctor4t.astronomical.client.AstronomicalClient tried to access private method "
Here is the report : https://pastebin.com/3vFC9PVT
I am french btw

**Comment by Xiribidus** [comment]
Solution:
Update Astronomical to [1.0.1](https://modrinth.com/mod/astronomical/version/1.0.1+1.19.2) and
update QFAPI to [0.76.0](https://modrinth.com/mod/qsl/version/4.0.0-beta.30+0.76.0-1.19.2)
