### ISSUE TITLE
BUG REPORT: Crashes with create when using the "ponder" feature.

### ISSUE THREAD

**Issue by SprunkledotDEV** [Ladysnake/Astronomical#6]
It seems this mod is somehow conflicting with create when rendering the "ponder" menu? I've read through the crash log and it seems like it. I can replicate the issue if i have both of them on and try to ponder, and pondering works fine with this mod disabled.

Additionally it renders planet displays without any issues so that's a plus. 

Crash log:
https://mclo.gs/s1xmNQy

Create version: v0.5.1c 
I haven't tried the other versions but i think its the issue with this mod.

**Comment by att1cu3** [comment]
It also seems to conflict with placing schematics

**Comment by ImDolos** [comment]
been having this issue as well

**Comment by namrask-office** [comment]
also have this issue

**Comment by doctor4t** [comment]
Fixed with 1.0.1
